name: Workflow test
on: push
jobs:
  Run-Test-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Npm install
        run: npm install
      - name: Run Actual testcases
        run: npm testpwd