name: Workflow test
on: 
  push:
    branches:
      - 'Dev'
  workflow_dispatch:
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Npm install
        run: npm install
      - name: Run Actual testcases
        run: npm test
  Build-Code:
    needs: Run-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install-Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: NPM-Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deplyed ..."